version: '3'
services:
  redis:
    image: redis:alpine
    container_name: school-redis
    command: --requirepass pass
    ports:
      - 6379:6379

  mysql:
    build: ./sql/
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: school-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    ports:
      - 33066:3306
    logging:
      driver: json-file
      options:
        max-size: 1k
    volumes:
      - mysql-store:/var/lib/mysql

volumes:
  mysql-store: